### PR TITLE
CCRAL: Fixed bug in drop_tree_ / drop / take_drop

### PR DESCRIPTION
**Pull request by rand00**
`drop_tree` drops everything when drop-count is equal length-1:
``` ocaml
# let l = CCRAL.(drop 2 @@ add_list empty [1;2;3]) ;;
val l : int L.t = <abstr>
# let _ = CCRAL.iter (Printf.printf "%d ") l ;;
- : unit = ()
```
This PR seems to do the right thing.

### CODE REVIEW

**Comment by c-cube** [comment]
Thank you for the report and fix. Can you add some tests that currently fail and are fixed by this, in the qtest format? Something like:

```ocaml
(*$T
  of_list [1;2;3] |> drop 2 |> length = 1
*)
```

also, add yourself to AUTHORS if you're not there ;)

**Comment by c-cube** [comment]
Thank you! 👍

**Comment by rand00** [comment]
I can't say that I fully understand the effects on the underlying tree structure of the change - might be good with a review if you havn't already looked at it.

And thank you for containers (:

**Comment by c-cube** [comment]
Thanks!

I'll make a second pass on it, but I think the idea is that `size` here represents the new size, which is not necessarily `2^n-1` as is normally the case because subtrees are complete binary trees.

**Comment by c-cube** [comment]
I'm adding tests and digging into that anyway.

**Comment by rand00** [comment]
Ah it also got more readable to me (:

**Comment by c-cube** [comment]
Yes, this code was written years ago, it could use a refactoring. And it's now also more readable for me!

**Pull request merged**
