### PR TITLE
Correction typos (fichiers src)

### PR DESCRIPTION
**Pull request by Fourchaux**
Corrections typos dans les seuls commentaires (des fichiers  du répertoire src)

### CODE REVIEW

**Comment by c-cube** [comment]
wow, is that the output of a tool? Pretty nice.

**Comment by Fourchaux** [comment]
Files changed 123. With my 2 mimines. Pfffffffffffffffff.......

(Rem: I forgot to erase 2 files inside /src/core : .merlin & .ocamlinit ).

**Comment by c-cube** [comment]
You should put yourself in `AUTHORS.adoc`, then I'll merge. Thanks for the hard work!

**Comment by Fourchaux** [comment]
Done

**Comment by c-cube** [comment]
Thank you! :-)

**Pull request merged**
