### PR TITLE
ocamldebug section in the README

### PR DESCRIPTION
**Pull request by nilsbecker**
This may be too long already?

### CODE REVIEW

**Comment by c-cube** [comment]
This seems good, but tests don't pass. Does `make` work locally for you (with mdx installed)?

**Comment by nilsbecker** [comment]
not really; i did `opam install mdx` then `make clean` then `make`. i get 
```
dune build   @install
dune runtest --no-buffer --force
Done: 671/680 (jobs: 2)Got an error while evaluating:
---
module M = struct let pp_int_list = Containers.(List.pp Int.pp) end
---
Characters 36-46:
Error: Unbound module Containers
         mdx alias runtest (exit 1)
(cd _build/default && /Users/nbecker/.opam/4.07.1+flambda/bin/mdx test README.md)
make: *** [test] Error 1
```

**Comment by nilsbecker** [comment]
ah wait. this is more sophisticated than i imagined -- my code examples are actually being built and run? i did not think they would need to be self-contained. can i just make this code block into an inline code snippet to prevent it from being built and tested?

**Comment by c-cube** [comment]
Yes, the readme is tested to prevent the code samples from becoming stale. Thank you for the patch!

**Pull request merged**
