### PR TITLE
wip: change API of CCBV (see #113)

### PR DESCRIPTION
**Pull request by c-cube**
keep track of changes for bitvectors.

### CODE REVIEW

**Comment by c-cube** [comment]
Ping @rleonid

**Comment by rleonid** [comment]
Oh wow talk about timing; I'm just getting my PR ready. I really got into the implementation and changed some things, such as using all 63 bits. I'll add a PR soon and we can compare. I'm still adding a few more tests.

**Comment by rleonid** [comment]
[this](https://github.com/rleonid/bitset_shootout/blob/new_containers/src/cn.ml) is my working version. PR, to follow later tonight or early tomorrow.

**Comment by c-cube** [comment]
Subsumed by #117

**Pull request closed without merging**
