### PR TITLE
predicate combinators: and_p and or_p

### PR DESCRIPTION
**Pull request by benbellick**

### CODE REVIEW

**Comment by c-cube** [comment]
should these perhaps be called `compose_and` and `compose_or`, as they're specialized version of `compose_binop`?

**Comment by benbellick** [comment]
Unless I am not understanding, it doesn't seem like a specialized version of `compose_binop`, as in `compose_binop`, the inside is the same function `f` applied to two terms `x` and `y`, whereas in `and_p` and `or_p`, the inside is two different functions `f` and `g` being applied to the same term `x`.

**Comment by c-cube** [comment]
Fair enough, there could be a `compose_binop_maxi f g1 g2 x y = f (g1 x) (g2 y)` that is actually a generalization of both. But my bad :). I'd still like a more descriptive name?

**Comment by benbellick** [comment]
The `p` I meant to evoke `predicate`, so how about `and_pred` or `and_predicate`?

**Comment by c-cube** [comment]
Sure, let's go with `and_pred` :)

**Comment by benbellick** [comment]
Done!

**Comment by c-cube** [comment]
thanks! :)

**Pull request merged**
