### PR TITLE
CCRingBuffer - a double sided polymorphic ring buffer

### PR DESCRIPTION
**Pull request by struktured**
Pretty confident on correctness, as I wrote a randomized test for every function of the signature. More interested in style and design feedback. 

Performance wise, there is an argument to be made that `blit_from_bounded` should use blit operations to batch the writes, but I don't think it's critical for the first release of this module.

### CODE REVIEW

**Comment by c-cube** [comment]
Merged manually. Thanks a lot, great work!

**Comment by c-cube** [comment]
Also changed a bit the interface and removed the `Array.Foo` modules that were mere polymorphic arrays.

**Comment by struktured** [comment]
I thought those Array.Foo versions were more efficient when explicitly implemented, per the [lexifi blog](http://www.lexifi.com/blog/about-unboxed-float-arrays), but it's very possible I misunderstood it.

**Comment by c-cube** [comment]
The blog post is a proposal, currently there is no efficiency gain but for Bytes.

**Pull request closed without merging**
