### PR TITLE
Add CCString.{,r}drop_while

### PR DESCRIPTION
**Pull request by kit-ty-kate**
I'm not sure about the name though. The function taken as argument is the opposite of what `CCString.filter` is waiting for but it made sense to me.
Any comments or suggestion on another name or if they should mimic `CCString.filter` ?

### CODE REVIEW

**Comment by c-cube** [comment]
That looks like a good idea. Possible names that come to me right now (not exhaustive list):

- `trim_by ~pred s`
- `trim_by ~skip_if s`
- `trim_pred f s`

**Comment by kit-ty-kate** [comment]
I like `drop{l,r}` but unfortunately there is already `CCString.drop : int ‑> string ‑> string`.
I like `trim_by` but I'm not sure whether `~pred` is the right name or not. What about not having a labelled argument there ?

**Comment by c-cube** [comment]
while not `{,r}drop_while f` then? would be consistent with `CCList.drop_while`

**Comment by kit-ty-kate** [comment]
@c-cube sold.

**Comment by c-cube** [comment]
thank you! :sparkles:

**Pull request merged**
