### PR TITLE
added List.counts, related to List.count

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by c-cube** [comment]
That looks like a useful function. Two remarks:

- please add yourself to the authors file
- I don't like the name, it's not explicit at all. How about something like `count_true_false`?

**Comment by UnixJunkie** [comment]
all done

**Comment by c-cube** [comment]
I think you included a "merge" commit instead of rebasing.

**Comment by UnixJunkie** [comment]
Yes, I'm not very good at git.
Squashing is perfect.

**Pull request merged**
