### PR TITLE
Enable support for Travis CI and Appveyor

### PR DESCRIPTION
**Pull request by jpdeplaix**
Done using @yomimono's [autoci](https://github.com/yomimono/autoci).

### CODE REVIEW

**Comment by c-cube** [comment]
Well, the travis check fails… Is it normal? :laughing:

**Comment by yomimono** [comment]
Nope! It's newly appearing in my test repository as well: https://travis-ci.org/yomimono/hello-tests/jobs/334482913#L5202 .  I think this is a new problem with `travis-opam` version 1.2.0.

**Comment by jpdeplaix** [comment]
For some reason some ubuntu images seem to use the system switch over a "clean" one :/
Otherwise for the versions that does have a proper switch:
```
#=== ERROR while installing containers.2.0 ====================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder runtest -p containers -j 4
# path                 /home/opam/.opam/4.06.0/build/containers.2.0
# compiler             4.06.0
# exit-code            1
# env-file             /home/opam/.opam/4.06.0/build/containers.2.0/containers-1861-05296d.env
# stdout-file          /home/opam/.opam/4.06.0/build/containers.2.0/containers-1861-05296d.out
# stderr-file          /home/opam/.opam/4.06.0/build/containers.2.0/containers-1861-05296d.err
### stderr ###
# Error: External library "sequence" not found.
# -> required by "qtest/jbuild (context default)"
# Hint: try: jbuilder external-lib-deps --missing -p containers @runtest
=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install containers 2.0
No changes have been performed
'opam install containers -t -v' failed.
'unset TESTS; OPAMYES=1 export OPAMYES; unset OPAMBUILDTEST; set -ue; opam install containers "-t" "-v"' exited 4. Terminating with 4
```

**Comment by c-cube** [comment]
Naive question: why ubuntu over alpine?

**Comment by yomimono** [comment]
> For some reason some ubuntu images seem to use the system switch over a "clean" one :/

Possibly related to https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md#testing-system-switches ?

> Naive question: why ubuntu over alpine?

A better-populated set of depexts.

**Comment by jpdeplaix** [comment]
This should fix the problem: https://github.com/ocaml/ocaml-ci-scripts/pull/219

**Comment by c-cube** [comment]
It seems that some libraries that are test-only deps are not installed. I think the jbuild files are fine, but I'm not totally sure.

```
Error: External library "sequence" not found.
- -> required by "qtest/jbuild (context default)"
```

**Comment by jpdeplaix** [comment]
Probably because your test-only deps are marked as optional. I'm not sure what you meant by that and I'm not sure what should be opam's behaviour either.

**Comment by yomimono** [comment]
Are the dependencies in the `depopts` field marked with `test` really optional (i.e., the tests that are run by `jbuilder build @runtest` can be built and run without them)?  Or perhaps they're there to work around some (possibly historical) wrong behavior of the test scripts?

**Comment by c-cube** [comment]
Good call, I guess? Should I also add the optional deps as required `{test}` deps?

**Comment by yomimono** [comment]
> Should I also add the optional deps as required {test} deps? edit: to run tests, these optional deps are necessary too

In that case (if I understand correctly) they should all be in `depends` with a `{test}` tag.

If you had additional tests that are only built if some dependencies are present (like, a flow where you opportunistically used `qtest` and `qcheck` to run some tests if you saw that `qcheck` was installed, but otherwise didn't) then it would be appropriate to put those in `depopts` with `{test}` tagged.

**Comment by jpdeplaix** [comment]
@yomimono if it is possible is there a problem to accept other kinds of optional dependencies [here](https://github.com/yomimono/autoci/blob/primary/src/opam.ml#L14) ? I'm really not sure what should be accepted (given the jbuilder circular dependencies for instance).
I suppose adding a least ```doc``` & ```test``` with opam 2.0 seems fine and with opam 1.2 given the lack of ```post``` attribute they would be broken anyway. Maybe, I don't know :/

**Comment by yomimono** [comment]
Yes, but that won't help - including the packages in DEPOPTS [just makes sure they're present for the test-with-depopts section of the test run](https://github.com/ocaml/ocaml-ci-scripts/blob/master/README-travis.md#optional-dependencies), not overall, so if they're always required and the installer script doesn't otherwise arrange for them to be present, the initial test build will fail.  Still, it's sensible to include the `{test}` tagged depopts in that variable at least, so I'll push a change including them.

**Comment by c-cube** [comment]
@jpdeplaix can you rebase on master? I moved test deps into `depends`

**Comment by jpdeplaix** [comment]
There is a failure on 4.04.2 only for some reason:
```
#=== ERROR while installing containers.2.0 ====================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder runtest -p containers -j 4
# path                 /home/opam/.opam/4.04.2/build/containers.2.0
# compiler             4.04.2
# exit-code            1
# env-file             /home/opam/.opam/4.04.2/build/containers.2.0/containers-4674-05296d.env
# stdout-file          /home/opam/.opam/4.04.2/build/containers.2.0/containers-4674-05296d.out
# stderr-file          /home/opam/.opam/4.04.2/build/containers.2.0/containers-4674-05296d.err
### stderr ###
# [...]
#    run_qtest alias qtest/runtest (exit 1)
# (cd _build/default/qtest && ./run_qtest.exe)
random seed: 305475584
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
# Failure: >split_list>../src/core/CCRandom.ml:229
# 
# ../src/core/CCRandom.ml:229:  run ~st:(QCheck_runner.random_state()) ( uniformity_test 50_000 (split_list 10 ~len:3) )
# ///////////////////////////////////////////////////////////////////////////////
# Ran: 1061 tests in: 12.87 seconds.                                        
# FAILURE
```

**Comment by c-cube** [comment]
That test can fail from time to time (with a low probability), I assume that's not the problem. Thanks for the changes! :smile:

**Pull request merged**
