### PR TITLE
use `stag` for color handling in CCFormat 

### LINKED ISSUE #403: use `stag` in Format
with preprocessor it becomes possible, see branch wip-format-stag .

- use new functions for `stag` on >= 4.08
- finish implementing `styling`
- provide more functions to bypass tag parsing (directly pass `Style of style list` instead)

### PR DESCRIPTION
**Pull request by c-cube**
close #403

### CODE REVIEW

**Comment by c-cube** [comment]
@favonia  you get the honor of trying this one out :) :)

**Comment by favonia** [comment]
I could not fully test it on OCaml 5 yet---[iter](https://github.com/c-cube/iter) also needs to be updated. However, the code itself (without the testing) compiles!

**Comment by favonia** [comment]
> [iter](https://github.com/c-cube/iter) also needs to be updated.

Never mind! It was already fixed on the master branch. I only need to pin it. The testing passed.

**Review by favonia — APPROVED** [review]
`dune runtest` passed with the current OCaml 5! :tada:

**Comment by c-cube** [comment]
Awesome, thank you for double checking! :)

**Pull request merged**
